### ISSUE TITLE
Welcome to Computing

### ISSUE THREAD

**Issue by tabinks** [uchicago-codes/MPCS50101-2017-Winter-Forum#1]
Please add a comment below.

**Comment by maeggert** [comment]
hello world

**Comment by tomzhu2004** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

**Comment by iyrdchtb** [comment]
Hello!

**Comment by sschumacker** [comment]
Hello hello

**Comment by janisza** [comment]
Howdy!

**Comment by arschw** [comment]
Hello!

**Comment by jcikalo** [comment]
hello!

**Comment by Gloria-Xiaolu-Zhang** [comment]
hello!

**Comment by joohoy** [comment]
Howdy

**Comment by sschwartz1** [comment]
Hello!

**Comment by bmbeller** [comment]
"Sometimes science is more art than science"

**Comment by arichards33** [comment]
Hello world!

**Comment by andrewkrutz** [comment]
Hello!

**Comment by alexichryss** [comment]
Hi?

**Comment by ccodette** [comment]
Hi

**Comment by kylebaum** [comment]
👍

**Comment by jonathanly93** [comment]
hello!
