### ISSUE TITLE
Office Hours - Hyde Park

### ISSUE THREAD

**Issue by nickflees** [uchicago-codes/MPCS50101-2017-Winter-Forum#101]
I'll be holding my office hours at my usual time in my usual place (6:30 - 8:30 PM in Young 111). Please let me know if you plan to attend and have not already done so. Thanks.

See you tonight.

**Comment by maeggert** [comment]
I will be there. A couple questions about #4 and #5.

**Comment by nickflees** [comment]
I may be a few minutes late tonight.

**Comment by ccodette** [comment]
Hi,
I plan on stopping by with a few questions on #4 and #7.
Chris
