### ISSUE TITLE
Problem 4

### ISSUE THREAD

**Issue by jonathanly93** [uchicago-codes/MPCS50101-2017-Winter-Forum#102]
I am a bit confused on what needs to be done for this problem.

Are we suppose to create a function product_of_odds that calculates the product of odds using map, reduce, and filter together or are we suppose to do create 3 separate functions for map, reduce, and filter and each of the functions are suppose to calculate the product of odds?

**Comment by nickflees** [comment]
You should use them together to define a single function that has a return statement as shown in the template.

**Comment by jonathanly93** [comment]
My current code only uses filter and reduce. So do I have to incorporate map into the function as well?

**Comment by jonathanly93** [comment]
Also the previous code:

def product_of_odds(list):
  result = 1
  for i in list:
    if i % 2 == 1:
      result *= i
  return result

will return 1 if there are no odd numbers. Is this mathematically correct? Say if you have a number list of 2,4,6,8,10 where none of the numbers are odd, will the product of the odd numbers be 1 or DNE?

**Comment by nickflees** [comment]
In mathematics, the product of an empty set is often defined to be 1. This is probably where the results 0! = 1 and x^0 = 1 for x != 0 come from. I'm not highly qualified to elaborate on this topic, but there's some interesting reading online if it's a topic you'd like to explore further. I started here: https://en.wikipedia.org/wiki/Empty_product.

**Comment by nickflees** [comment]
Also, in office hours, we discussed a solution that trivially incorporates map by mapping an identity function (e.g., `map(lambda x: x, my_list)`)

**Comment by tabinks** [comment]
That's no fun.  There will be different solutions to this problem.

**Comment by nickflees** [comment]
Sorry @tabinks  and @jonathanly93. I didn't mean to imply that was the only way to do it. You can get extremely creative with this one.
