### ISSUE TITLE
Office Hours List

### ISSUE THREAD

**Issue by tabinks** [uchicago-codes/MPCS50101-2017-Winter-Forum#13]
Here are the TAs office hours schedules:
* Nick (nickflees@gmail.com): 
  - Monday 6:30 PM at Young 111
* Rachel (rkillackey@uchicago.edu)
  - Tuesdays at 6PM at Gleacher 
* Jane( j.v.makin@gmail.com)
  - Monday at 6PM at Gleacher
* Andrew (abinkowski@uchicago.edu)
  - Thursday at 10:00PM at Young 308

If you are planning on attending a session, please let us know so we can plan accordingly.

**Comment by nickflees** [comment]
Minor correction: Mine start at 6:30 on Mondays.

**Comment by tabinks** [comment]
Fixed.
