### ISSUE TITLE
Monday Office Hours

### ISSUE THREAD

**Issue by nickflees** [uchicago-codes/MPCS50101-2017-Winter-Forum#14]
Hi Everybody,

A couple of students have reached out regarding office hours tomorrow. I am still planning on holding them, despite the holiday, but I understand that all campus buildings are closed, so I'm looking for another location. I'll post here once it's settled.

I'm still planning on 6:30 PM as the start time.

Nick

**Comment by tabinks** [comment]
@nickflees Thanks Nick.

**Comment by nickflees** [comment]
My tentative plan is to be at Starbucks at Grand and Ogden (520 N Ogden) at 6:30. Please let me know if you are planning to attend but for some reason object to the location.

**Comment by jvmakin** [comment]
It looks like the A-level in the Reg is open, if that helps you :)

https://www.lib.uchicago.edu/using/libraries-hours/

**Comment by nickflees** [comment]
Thanks, Jane. Im not sure if my TA ID gets me into the Reg. I'm going to stick with Starbucks as long as that works for everyone.
