### ISSUE TITLE
Office Hours Deux (Jane's office hours tonight)

### ISSUE THREAD

**Issue by jvmakin** [uchicago-codes/MPCS50101-2017-Winter-Forum#18]
Hello Chickies,

I will also be holding office hours today at 6 PM at the Gleacher Center (downtown/Booth School Region). I'll be situated in the Cafeteria, which is on the first floor to the left of the entrance. Come with questions, syntactical errors, and general Python related panic.

**Comment by tabinks** [comment]
@jvmakin I am not sure if Gleacher will be open today.  It may be since the building is owned independently of the University.  Do you have a backup location nearby just in case?  There has to be a Starbucks nearby.

**Comment by jvmakin** [comment]
I called them and they said that the cafeteria is open but there is no food served. :)

I'll get there a little early, but if all else fails there is a coffee shop right next to Gleacher.

**Comment by tabinks** [comment]
That was a very good idea.  Sometimes I forget that you can use a phone for calling.
