### ISSUE TITLE
HW2 general question

### ISSUE THREAD

**Issue by bmbeller** [uchicago-codes/MPCS50101-2017-Winter-Forum#20]
Should we be prompting the user for input in every question? Or should we be writing general functions where the desired input would be entered in python after you construct your function?

**Comment by tabinks** [comment]
Problems 1, 2, and 5 require user input.  For the others, just write out the functions  We will be running your code to test it.  As part of your normal development/testing cycle, you should be using your function.  Just leave your function call in your code for us to test as well.
