### ISSUE TITLE
HW3- Q2 question

### ISSUE THREAD

**Issue by bmbeller** [uchicago-codes/MPCS50101-2017-Winter-Forum#28]
When you say robust temperature converter, do you want our function to work for an input  like "80F" (i.e. remove the F and convert 80 Fahrenheit to Celsius) or do you just want to make sure that the function does not break? Thanks

**Comment by nickflees** [comment]
My interpretation is that the program should check that the input is numeric and convertible to a numerical type (whether integer or floating point). A suitable implementation could be to prompt the user for input again with an error message if the original input is not entirely numeric. In other words, if a user enters 80F, print an error message like "Input must be numeric" and then prompt again for input.

**Comment by bmbeller** [comment]
thanks nick!

**Comment by tabinks** [comment]
@bmbeller What Nick said was correct.  Just make sure that the program doesn't break.
