### ISSUE TITLE
Q6 question

### ISSUE THREAD

**Issue by maeggert** [uchicago-codes/MPCS50101-2017-Winter-Forum#29]
Do we need to deal with the word "applause' that shows up between parentheses? It's not really part of the speech, but some could find it interesting to have a count of how many times it occurred.

**Comment by jvmakin** [comment]
Since the purpose of problem 6 is text analysis, you still ought to return the top 20 words from the text of the speech. If you want to make a note of the applause (perhaps store the number of times you find the word applause as a separate variable), go bananas! It is a cool idea. 👍

**Comment by tabinks** [comment]
@maeggert Good catch.  Technically, it was not spoken text so you shouldn't keep track of it.  However, it is just an outlier on the formatting of the speech, so if you left it in that will be fine.  I think it would be interesting to compare the applause to other speeches.
