### ISSUE TITLE
Question 5: closest points part

### ISSUE THREAD

**Issue by maeggert** [uchicago-codes/MPCS50101-2017-Winter-Forum#30]
I believe my program correctly finds which point is closest to the origin, but I am struggling with how to check each point against one another while keeping track of the min. Any suggestions?

**Comment by jvmakin** [comment]
Are you having trouble plugging the points into the distance formula? Or just keeping track of the minimum? 

If you aren't sure the distance formula is working, try printing out the output at various times in the program (is it squaring correctly? subtracting correctly? etc.?) and comparing to this calculator:
http://www.calculatorsoup.com/calculators/geometry-solids/distance-two-points.php
 
To keep track of the minimum, I'll give you some handy psuedocode. With a small tweak, this will also work for finding the maximum:
set min = infinity 
for values: # in this case your distances
         if value < min:
               min = value
return min

As a note, you could also run the function within the for loop (set value = function(a, b)) so you don't have to store them.

**Comment by jvmakin** [comment]
p.s. The python code for infinity is: float("inf")

**Comment by tabinks** [comment]
Yes, the trick to keeping track of a min/max number is to set a default value that will never be less than/greater than what you will see in the comparison.

**Comment by maeggert** [comment]
Thanks for the pseudo code. I actually have something pretty similar. I think the issue I am having may be more with also keeping track of what the corresponding points in the dictionary are that yield the min. So with my dictionary of 4 points, I need to compare point 1 to: 2, 3, and 4, then point 2: to 3 and 4, and finally compare point 3 to point 4. So it seems like I need to keep track of which two points were being compared when I obtained the min distance. I fear I may be missing something obvious

**Comment by jvmakin** [comment]
Okey dokey! 

You are correct that you need to keep track of the points being compared as well as the min distance. If you're running the distance function within the for loop (as in when you're checking whether its a minimum distance) then that's pretty easy. Set two variables equal to the names/indexes/whatever of the two points when you find a min (this would be done the same way as the min value itself - set beforehand and reset within). 

If you're using a dictionary, you could use the key as an index as its then easy to get the actual values out of the dict. 

I hope that's clearer!

**Comment by maeggert** [comment]
Thanks for all the help. I think I got something that works, but I can't imagine it is the best way. I will stop by some office hours to look into making my solution better,

**Comment by jvmakin** [comment]
Look forward to seeing you there. 

The key to successful programming is finding a hacky way of making it work and then polishing. Godspeed.
