### ISSUE TITLE
Common Words

### ISSUE THREAD

**Issue by sschumacker** [uchicago-codes/MPCS50101-2017-Winter-Forum#32]
It appears that the links to the 'common words' text file for Assignment 4 are broken. There are two links, one in problem 5 and one in the Unix Challenge description.

Link: http://uchicago.codes/sessions/session4/common_words.txt

My assumption is that the format (if not the file itself) is the same as 'common_words_100.txt' we used in Assignment 3, in which case the specific words are immaterial as long as we can use them for hangman / sort them. So, not really a significant issue (apart from the strange experience of playing hangman with words like 'its', 'the', etc), but just FYI.

**Comment by tabinks** [comment]
It was the exact same list. Please download the one from the previous assignments. I will update the link later this afternoon.  

 Sometime short words are fun too.

**Comment by sschumacker** [comment]
Understood - thank you

**Comment by tabinks** [comment]
If you want to improve the difficulty of your game, you can remove short words from the list. If you want to  another UNIX challenge, use the command AWK and you can filter The lines in a file by their length.

**Comment by tabinks** [comment]
Here's a working link in the meantime: http://uchicago.codes/sessions/session3/common_words.txt
