### ISSUE TITLE
HW2 Resubmission

### ISSUE THREAD

**Issue by sschwartz1** [uchicago-codes/MPCS50101-2017-Winter-Forum#34]
For the hw resubmission, do we just resubmit the problems that are being redone to our master branch for that assignment with a message saying its for resubmission?

**Comment by jvmakin** [comment]
Yes - resubmit in the same place! Also, it would be helpful to let your grader know so we don't miss it...

**Comment by tabinks** [comment]
Yes, send a quick email to graders.
