### ISSUE TITLE
hw4 problem 1

### ISSUE THREAD

**Issue by sschwartz1** [uchicago-codes/MPCS50101-2017-Winter-Forum#35]
We were told to use the try and except function in our code last week. If we use that, we won't get any conversion errors to test for. Should we ignore the conversion error test then or get rid of the try and except part of the code?

**Comment by tabinks** [comment]
You could do it that way or another way of doing it would to be to test for the condition that no error was raised during the conversion.  Either approach would be valid and acceptable.
