### ISSUE TITLE
Office Hours - Jane Edition

### ISSUE THREAD

**Issue by jvmakin** [uchicago-codes/MPCS50101-2017-Winter-Forum#37]
Hey Kittens,

I'll be holding office hours tonight in the Gleacher Center cafeteria at 6 PM. Let me know if you plan to attend, otherwise I may play hooky in the glorious sunshine...

**Comment by arichards33** [comment]
Hi Jane - I'm planning on attending, sorry to ruin your plan to play hooky! :-/

**Comment by janisza** [comment]
Hi Jane, late addition but I'm planning to attend also. See you there!
