### ISSUE TITLE
Office Hours - Nick Edition

### ISSUE THREAD

**Issue by nickflees** [uchicago-codes/MPCS50101-2017-Winter-Forum#38]
Hi everybody,

I'll be holding my office hours again tonight in Young 111 from 6:30 until 8:30. Please drop me a line if you plan to attend.

Thanks.

Nick

**Comment by maeggert** [comment]
I am planning to stop by. I have some questions about unit testing and recursively going through a directory

**Comment by nickflees** [comment]
@maeggert Great. See you tonight.

**Comment by ccodette** [comment]
Hi,
I have some questions about the same problems. I will be stopping by as well.
Chris

**Comment by jcikalo** [comment]
I'll be attending.
