### ISSUE TITLE
Homework5 Problem2 

### ISSUE THREAD

**Issue by joohoy** [uchicago-codes/MPCS50101-2017-Winter-Forum#45]
What exactly are we supposed to deliver for problem 2? After going through the Interactive Tutorial and Practice Problems, all RegexOne requires is one line of regular expression to solve their problem. Are we supposed to type the regular expression code that solves the problem into a file and send it in?

**Comment by tabinks** [comment]
![screenshot 2017-02-03 13 37 19](https://cloud.githubusercontent.com/assets/93689/22605543/eb32cbc4-ea15-11e6-8c65-18961d9b812b.png)

Go through and type out each of the four samples they work through and submit the files.  It's good practice to type them out and get to play with the code samples (as opposed to just reading through them).

**Comment by jcikalo** [comment]
So to clarify your above statement, do we we only submit the four samples in separate files for https://regexone.com/references/python?  For https://regexone.com/lesson/introduction_abcs, we go through each lesson and problem, but do not submit the patterns?  Or for each of the 15 lessons and 8 problems, do we submit what our pattern is?

**Comment by tabinks** [comment]
For the 'abc', you do not need to submit anything.  Submit the four files for the python based lesson.
