### ISSUE TITLE
HW 5 Problem 4

### ISSUE THREAD

**Issue by sschwartz1** [uchicago-codes/MPCS50101-2017-Winter-Forum#46]
There doesn't seem to be a link to the list of allowable scrabble words for problem 4. Also do we want the user to input any number of tiles or just 3 tiles?

**Comment by sschumacker** [comment]
I was wondering the same, but pending an official answer, it's probably any number. 'enter thee tiles in their rack' reads as 'three' at a glance but makes more sense as 'the', since the examples all have 4 letters.

**Comment by tabinks** [comment]
@sschumacker @sschwartz1 Link is fixed on the site.  Here it is: http://uchicago.codes/sessions/session5/scrabble_list.txt

**Comment by tabinks** [comment]
Just a note that while you can make words longer than 7 characters in Scrabble using other played tiles, this list only shows 53,901 valid words that can be made with <=7 characters.

Unix tip of the day: The command `wc` (word count) will count the lines and/or characters in a file from the terminal.
```bash
% wc scrabble_list.txt 
53901   53901  380889 scrabble_list.tx
```
