### ISSUE TITLE
HW 5 Problem 5

### ISSUE THREAD

**Issue by jonathanly93** [uchicago-codes/MPCS50101-2017-Winter-Forum#49]
Will we be docked off points if our program runs slower for larger words? It takes my program about 15 seconds to run a 7 tile word.

**Comment by nickflees** [comment]
I suppose it depends on why it runs slowly. We don't expect you to be an expert in optimizing your code for speed. On the other hand, if there's a problem with your algorithm that, in the grader's estimation, is something you should have been able to resolve, then it's possible that it could affect your score.

**Comment by tabinks** [comment]
Doing an exhaustive enumeration of all possible combinations and permutations of a set is one of the most time consuming things you can do in a program.  Most algorithms aim to approximate this behavior to achieve better performance with acceptable results.  That time sounds reasonable to me, but Nick is correct that you should make sure that you are doing anything that contributes negatively to the run time.
