### ISSUE TITLE
Assignment 1 question

### ISSUE THREAD

**Issue by maeggert** [uchicago-codes/MPCS50101-2017-Winter-Forum#5]
Does anybody know if the 5 exercise files should be submitted as they would be **before or after** doing the study drills at the end of each exercise?

**Comment by tabinks** [comment]
You can submit either way.  You do not have to complete the study drills.  Do as many as you feel will be beneficial to you.

**Comment by sschwartz1** [comment]
It says to email the 5 exercises to the instructor, but there doesn't seem to be the email anywhere. What's the email we should send it to?

**Comment by alexichryss** [comment]
@sschwartz1 I used the mailto: link at the bottom of the [uchicago.codes](url) ([abinkowski@uchicago.edu](url) for reference)

**Comment by tabinks** [comment]
You only need to email me.  I will share with the TAs.
