### ISSUE TITLE
HW5 problem 1

### ISSUE THREAD

**Issue by bmbeller** [uchicago-codes/MPCS50101-2017-Winter-Forum#50]
Is it fine if we just use one function (words()) to accomplish all the required tasks or would you rather us create several modules then have words() call those modules?

**Comment by tabinks** [comment]
While you could use one function, this would be not be a 'best practice'.  You should factor out the work to be done in functions.  You only need to create one module with multiple functions.

**Comment by bmbeller** [comment]
got it, thanks!
