### ISSUE TITLE
Homework5 Problem 3

### ISSUE THREAD

**Issue by jcikalo** [uchicago-codes/MPCS50101-2017-Winter-Forum#51]
Had a question for 3, how are we being graded on this problem?  Are we suppose to attempt on our own the problem, and if we get stuck, use the solution?  My notes from class say:

o   Read the write up
o   Part a and part b
o   Take a look at it
o   Open up their solution

Just want to make sure I understand the direction on how to proceed.  Thanks in advance.

**Comment by tabinks** [comment]
You should turn in a working solution to the Parts A and B.  The exact approach you take to doing this is up to you.  You goal should be to understand how to solve (and be able to implement a similar solution if required to in the future).
