### ISSUE TITLE
HW5 Problem #4 question

### ISSUE THREAD

**Issue by maeggert** [uchicago-codes/MPCS50101-2017-Winter-Forum#55]
Does anybody have thoughts on whether it is better to write a regular expression that will match to any of the three kinds of input or...writing three different regular expression searches, one for input with spaces, one for no spaces, and one for commas. You could then evaluate which of those searches came back true, and go from there.

**Comment by alexichryss** [comment]
You can write one regular expression that will handle alphas, whitespace, or commas. User brackets in regex to handle OR.

**Comment by maeggert** [comment]
Thanks for the tips. I will play around with those ideas
