### ISSUE TITLE
hw5p4

### ISSUE THREAD

**Issue by ddeng50101** [uchicago-codes/MPCS50101-2017-Winter-Forum#56]
Hi! Do we have to use the itertools module for this problem? If we find a more efficient way to identify all the possible scrabble words, would that be acceptable for the homework?

**Comment by nickflees** [comment]
The object is to identify the possible permutations of letters you can create from a given set of letters that also happen to be legal scrabble words. The iterations package gives you a method to do that. Are you asking if you can create your own permutation algorithm?

**Comment by ddeng50101** [comment]
Yes - to identify all the possible scrabble without using the iteration module. Or do we have to use this module?

**Comment by nickflees** [comment]
The list of possible words is given in a file. The task involves scrubbing your list of permutations against that list.

Can you be more specific about what you are proposing to do?

**Comment by tabinks** [comment]
Yes, please use the module.  Iit will be much, much, much easier than writing your own.
