### ISSUE TITLE
Office Hours (Hyde Park)

### ISSUE THREAD

**Issue by nickflees** [uchicago-codes/MPCS50101-2017-Winter-Forum#61]
I'll also be holding office hours tonight at my usual time and place (6:30-8:30, Young 111).

If you're planning to attend, please respond here (if you haven't already told me). Also, as @jvmakin requested in her post, if there's a specific question or topic you want to discuss, please let me know. It will help me prepare to help you as effectively as I can.

See you tonight.

**Comment by maeggert** [comment]
I am going to stop by with some questions about number 3

**Comment by ccodette** [comment]
Hi,
I plan to stop by with a few questions on problems 5 and 6.
Chris
