### ISSUE TITLE
Problem 6 

### ISSUE THREAD

**Issue by ddeng50101** [uchicago-codes/MPCS50101-2017-Winter-Forum#64]
"Once you have all of you robots, you should create an programmatic interface to search for all the good and bad robots. Identify the good and bad robots, keep a list of them by their ids and print that list to the console." 

slightly confused about this - is the end goal to generate two lists of two robots? do the attributes we write for GoodRobot & BadRobot matter?

**Comment by tabinks** [comment]
@ddeng50101 The end goal is to use have the two lists of robots.  The attributes don't really matter.  Just create something that shows that you understand how to define and use attributes on a subclass.
