### ISSUE TITLE
HW6, problem 3 (checking values)

### ISSUE THREAD

**Issue by janisza** [uchicago-codes/MPCS50101-2017-Winter-Forum#65]
In problem 3, since we're defining a fraction class, what is the intent of checking that the values are valid for a fraction, and what should our script do instead? For example, if I type:

print Fraction('pancakes', 'waffles'),

Python automatically returns a TypeError (as I'd expect). In the same way, Python will return a similar TypeError if I tried to make it do: 'panda' * 'sunglasses'. Are we supposed to give our fraction class some other type of functionality to do something different?

**Comment by nickflees** [comment]
A simple approach would be to check that the values passed to your constructor (i.e., __init__) are integers and to raise an error if they are not.

**Comment by tabinks** [comment]
Yes, the intent of checking is to ensure that the values entered are numbers.  Also, that they are valid in terms of the mathematical operations that will be done on them (eg. divide by zero prevention).

**Comment by janisza** [comment]
Got it, so raising a ZeroDivisionError (denominator = 0) or a TypeError (pancake fraction) satisfies the intent of the value checking?

**Comment by nickflees** [comment]
@janisza, yes. Implementing type and value checking in your constructor using exceptions is one way to do this. Keep in mind, however, that in the code you write to use this class, you may need to use a try/except pattern to catch the exception/error raised by the constructor when an inappropriate value is used.

In other words, let's say you implement the Fraction class's constructor to raise a TypeError when a non-integer value is used and to raise a ZeroDivisionError when the denominator argument is 0. If I try to create an instance of the class like this

frac = Fraction('waffle', 'pancake')

The constructor will raise the TypeError. My program that is attempting to instantiate the class should be robust enough to catch that TypeError and handle it gracefully. This will be similar to the work you've already done on other assignments where you have to handle errors. Something like this might be appropriate:

try:
    frac = Fraction(numerator, denominator)
except TypeError:
    print 'numerator and denominator must be integers'
except ZeroDivisionError:
    print 'denominator must be non-zero'

There are all kinds of ways that this might end up being implemented, but that's just an idea of what you might look out for.

Having said all that, you'll find a lot of disagreement among Python programmers on what the appropriate way is to do this.
