### ISSUE TITLE
Hw7 Problem 5

### ISSUE THREAD

**Issue by jcikalo** [uchicago-codes/MPCS50101-2017-Winter-Forum#73]
For problem 5, do we turn in the "self check" portions as well or just the foundation of UnorderedList?

**Comment by bmbeller** [comment]
Also just making sure on question 5- we have to make our own append, insert, index, and pop methods for unordered and ordered lists right?

**Comment by andrewkrutz** [comment]
I'm also confused about the exact deliverable we should have.

**Comment by tabinks** [comment]
Yes, turn in the self check portions.  Show us that it worked!

**Comment by tabinks** [comment]
@bmbeller Yes, you should have your own methods implemented for them.  Most will be similar, if not identical.
