### ISSUE TITLE
General HW7 Question

### ISSUE THREAD

**Issue by sschwartz1** [uchicago-codes/MPCS50101-2017-Winter-Forum#77]
Besides using the created data structure (Stack, Deque, Ordered lists), are our programs still allowed to use python standard data structures like lists?

**Comment by nickflees** [comment]
In general, yes, but I think the point of this current assignment is to use these custom data structures, so I would be cautious about it. Can you be more specific about where and how you want to use the native data structures?

**Comment by sschwartz1** [comment]
For problem 1 in my user input function, I basically filter out any non balanced symbols and for part of that I use a list to do some of it. In the actual balanced symbol test function I use the stack data type.

**Comment by tabinks** [comment]
@sschwartz1 What you described is fine.  You should only be using these new data structures for the specific parts that require them.  The idea is to make it easier, not harder.
