### ISSUE TITLE
problem 4

### ISSUE THREAD

**Issue by ddeng50101** [uchicago-codes/MPCS50101-2017-Winter-Forum#80]
"Using the Deque data structure from above, write a program that identifies if a given word is a palindrome."

Should we assume user_input will be a letter only word? or as in the previous assignment, we are expected to identify whether "never_odd_or_even" is a palindrome?

**Comment by rkillackey** [comment]
I believe you will also need to handle all the same cases as the previous assignment (i.e., not just single words, but also phrases).

**Comment by tabinks** [comment]
You should handle these different cases.  Reuse your code from the earlier assignment.
