### ISSUE TITLE
Make-up office hour schedule

### ISSUE THREAD

**Issue by jcikalo** [uchicago-codes/MPCS50101-2017-Winter-Forum#86]
Just wanted to confirm that the makeup office hours will be Monday (and at what time).  Thanks.

**Comment by jvmakin** [comment]
I will be holding my normal office hours, if that what you mean!

**Comment by jcikalo** [comment]
Hi Jane,
Sorry for the confusion.  I meant to say the make-up of Prof. Binkowski's office hours (from Thursday).  It's usually easier for me to drive straight to campus on Mondays, so I thought I'd see what time I'd have to leave from work (and adjust any scheduling accordingly).

**Comment by tabinks** [comment]
#88
