### ISSUE TITLE
hw8 p6

### ISSUE THREAD

**Issue by maeggert** [uchicago-codes/MPCS50101-2017-Winter-Forum#94]
I am struggling with the best way to go about the 100 timing benchmarks. Do we want to time both our binary search and linear search 100 times (each time searching for a different word), and just take the average?

**Comment by tabinks** [comment]
That's pretty much it.

**Comment by jvmakin** [comment]
It would also be interesting to see if there is any difference between search times (for both linear and binary) for a word at the beginning of the list, a word in the middle of the list, and a word not in the the list. 

Not mandatory, but nifty.

**Comment by maeggert** [comment]
And then for comparing the times, do we time the binary search assuming it is passed a sorted list, or do we want to include the time taken to sort the list (since that is a prerequisite for binary search).

**Comment by jvmakin** [comment]
I'm assuming, since you were allowed to use the list sorting methods in Problem 5, that you can use those again here. In that case, you can assume it is passed a sorted list as the time to do so should be negligible.

My previous comment would also require a sorted list for an interesting comparison.

**Comment by nickflees** [comment]
As a follow-up to this, it's important to note that whether the list is sorted makes all the difference in the general relative performance between searching a list of size n in a binary or a linear fashion.

For linear search, it's asymptotically irrelevant whether the list is sorted. It's O(n) either way. Binary search, however, won't return meaningful results on an unsorted list, so you have to incur the O(n * lg n) cost of sorting it if you cannot rely on it having been sorted already. The sorting step is the difference between it being more efficient than linear search and it being inferior.

O(lg n) < O(n) < O(n * lg n) as n -> infinity

**Comment by maeggert** [comment]
So when deciding whether or not to use binary search, it would probably make sense to consider how many times you will be searching the list. Is that accurate? If you are just searching it once, you will never get better performance with binary search because you will have O(n log n) to sort the list first (and linear search would have been O(n)). But if you will be searching the list a lot, you could just sort it once and from there, binary search will be O(log n) each time as opposed to O(n) with linear search (which could lead to O(n^2) if searching the list n times.

**Comment by nickflees** [comment]
That would certainly be one consideration. As @tabinks discussed in class last night, you might also consider other ways to sort and whether you expect that the collection is already nearly sorted. Though the worst case performance of sorting algorithms like bubble and insertion sort is O(n^2), they can perform nearly linearly for nearly-sorted collections.
