### ISSUE TITLE
Question about timeit

### ISSUE THREAD

**Issue by joohoy** [uchicago-codes/MPCS50101-2017-Winter-Forum#96]
In this upcoming homework, we are asked to compare speeds of different functions. For the reading for our previous homework, there was an example where the author used timeit to run the function a certain number of times and report how long it took to run in seconds. It certainly seems much more elegant than using start and end at the beginning of every function and iterating 100 times to see how long it takes.

https://interactivepython.org/runestone/static/pythonds/AlgorithmAnalysis/Lists.html
t1 = Timer("test1()", "from __main__ import test1")
print("concat ",t1.timeit(number=1000), "milliseconds")

However, to actually use Timer for our homework problems, we need to include a variable in the first statement of Timer, where the "test1()" is. I kept on getting an error until I made the first statement 
lambda: "test1(variable)". I fear that this is not correct because while it runs and spits out a time, it reports a runtime much faster than the start and end time method and doesn't seem to take longer when I grow the size of the variable (which it should).

 What do I need to change to effectively run timeit with a variable?

**Comment by tabinks** [comment]
I personally haven't used the `timeit` module before.  I use something like this instead:

```
import time
class Timer(object):
    def __enter__(self):
        self.start = time.time()
        return self

    def __exit__(self, *args):
        self.end = time.time()
        self.secs = self.end - self.start
```
To use it, you just wrap you function (or statement) calls inside:
```
with Timer() as t:
    run_my_function()
print t.secs
```

The one thing about the active development community in Python is there are always many ways and approaches to solving a problem.  If you find one working against you, keep looking...or write your own.
